### ISSUE TITLE
[Crash] Crash involving Create, stating the error "failed to create mod instance", and involving cypress windows from this mod.

### ISSUE THREAD

**Issue by Corvus20** [teamauroramods/BayouBlues-Forge#37]
I don't really know what else to say here. Testing shows that removing bayou blues results in no crash. So its some sort of conflict or compatibility issue between the two mods. I've attached the crash report below.

[crash-2021-06-16_20.56.41-fml.txt](https://github.com/teamauroramods/BayouBlues-Forge/files/6666720/crash-2021-06-16_20.56.41-fml.txt)

**Comment by ShockMicro** [comment]
Abnormals Core has an issue with Create as of right now, try downgrading your Abnormals Core by a version and see if that works.
